<?php

use App\Models\Institution;
use Illuminate\Database\QueryException;

/**
 * F1-03 against a production-style base domain: {subdomain}.tusistema.com
 * resolves to that institution, and everything the tenant generates (links,
 * redirects) stays on that subdomain. Nothing may depend on the local
 * aulaix.test domain.
 */
beforeEach(fn () => useAppDomain('tusistema.com'));

test('colegio.tusistema.com loads the colegio institution', function () {
    tenant(['subdomain' => 'colegio', 'name' => 'Colegio San José']);
    tenant(['subdomain' => 'liceo', 'name' => 'Liceo Andrés Bello']);

    $this->get('https://colegio.tusistema.com/login')
        ->assertOk()
        ->assertInertia(fn ($page) => $page
            ->component('Auth/Login')
            ->where('institution.subdomain', 'colegio')
            ->where('institution.name', 'Colegio San José')
            ->where('appDomain', 'tusistema.com')
        );

    $this->get('https://liceo.tusistema.com/login')
        ->assertInertia(fn ($page) => $page->where('institution.subdomain', 'liceo'));
});

test('the subdomain is matched regardless of letter case', function () {
    tenant(['subdomain' => 'colegio']);

    $this->get('https://Colegio.TuSistema.com/login')
        ->assertInertia(fn ($page) => $page->where('institution.subdomain', 'colegio'));
});

test('redirects generated by a tenant stay on its subdomain', function () {
    tenant(['subdomain' => 'colegio']);

    $this->get('https://colegio.tusistema.com/dashboard')
        ->assertRedirect('https://colegio.tusistema.com/login');
});

test('the bare domain shows the institution selector', function () {
    $this->get('https://tusistema.com/')
        ->assertOk()
        ->assertInertia(fn ($page) => $page->component('SelectInstitution'));
});

test('www redirects to the institution selector instead of being treated as a tenant', function () {
    $this->get('https://www.tusistema.com/')
        ->assertRedirect('https://tusistema.com/');
});

test('hosts outside the base domain resolve nothing', function (string $host) {
    tenant(['subdomain' => 'colegio']);

    $this->get("https://{$host}/login")->assertNotFound();
})->with([
    'the local development domain' => 'colegio.aulaix.test',
    'a look-alike domain' => 'colegio.tusistema.com.evil.com',
    'a nested subdomain' => 'x.colegio.tusistema.com',
    'an unknown institution' => 'otro.tusistema.com',
]);

test('a subdomain is stored lower-cased and trimmed', function () {
    $institution = Institution::factory()->create(['subdomain' => '  Colegio-Norte ']);

    expect($institution->fresh()->subdomain)->toBe('colegio-norte');
});

test('a subdomain must be a valid DNS label', function (string $subdomain) {
    expect(fn () => Institution::factory()->create(['subdomain' => $subdomain]))
        ->toThrow(QueryException::class, 'institutions_subdomain_format');
})->with([
    'with a dot' => 'colegio.norte',
    'with an underscore' => 'colegio_norte',
    'starting with a hyphen' => '-colegio',
    'ending with a hyphen' => 'colegio-',
    'too long' => str_repeat('a', 64),
    'empty' => '',
]);

test('reserved subdomains can not be used by an institution', function (string $subdomain) {
    expect(fn () => Institution::factory()->create(['subdomain' => $subdomain]))
        ->toThrow(QueryException::class, 'institutions_subdomain_format');
})->with(Institution::RESERVED_SUBDOMAINS);
